[package]
name = "advent-of-code-2020"
version = "0.1.0"
authors = ["atgJack <some@one.anon>"]
edition = "2018"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
indoc = "1.0.3"
nom = "6.0.1"
